@extends('layouts.main')
@section('title', 'About us')
@section('content')
    <div class="container">
        <div class="row p-t-20">
            <div class="col-md-12">
                <h1>Termini di utilizzo del sito</h1>
                <p><strong><u>Si</u></strong> <strong><u>prega</u></strong> <strong><u>di</u></strong> <strong><u>leggere</u></strong> <strong><u>attentamente</u></strong> <strong><u>i</u></strong> <strong><u>presenti</u></strong> <strong><u>termini</u></strong>. </p>
                <p>Il presente sito Internet <a href="http://www.orangogo.it">www.orangogo.it</a> (nel seguito, in breve, il &ldquo;Sito&rdquo;) &egrave; rivolto a coloro che cercano servizi sportivi e ha la finalit&agrave; di aiutare i propri visitatori (nel seguito, in breve, &ldquo;Utente/i&rdquo;) nell&rsquo;individuazione dell&rsquo;Associazione o Societ&agrave; (di seguito &ldquo;Organizzazione Sportiva&rdquo;) che meglio risponde alle proprie esigenze, tra quelle presenti sulla piattaforma OrangoGO (la &ldquo;Piattaforma&rdquo;).</p>
                <p>I termini di utilizzo (in breve "Termini di Utilizzo"), di seguito riportati, e l'informativa sul trattamento dei dati personali, di cui alla pagina web https://www.orangogo.it/privacy, disciplinano l'utilizzo, da parte degli Utenti e/o delle Organizzazioni Sportive, del Sito e di tutto il materiale in esso contenuto, ivi compresi i relativi sottodomini, o della Piattaforma.</p>
                <p><strong>Attraverso</strong> <strong>l</strong><strong>&rsquo;</strong><strong>utilizzo</strong> <strong>del</strong> <strong>Sito</strong><strong>, </strong><strong>ciascun</strong> <strong>Utente</strong> <strong>e</strong><strong>/</strong><strong>o</strong> <strong>Organizzazione</strong> <strong>Sportiva</strong> <strong>d&agrave;</strong> <strong>atto</strong> <strong>di</strong> <strong>aver</strong> <strong>letto</strong> <strong>e</strong> <strong>compreso</strong> <strong>i</strong> <strong>presenti</strong> <strong>Termini</strong> <strong>di</strong> <strong>Utilizzo</strong> <strong>e</strong> <strong>dichiara</strong> <strong>pertanto</strong> <strong>di</strong> <strong>accettarli</strong> <strong>espressamente</strong><strong>.</strong></p>
                <p>Il marchio OrangoGO, il Sito e tutti i materiali in esso disponibili, ivi compresi i relativi sottodomini, come la Piattaforma sono di titolarit&agrave; di Sport Grand Tour Srl con Sede Legale in Via Maria Vittoria 38, 10123 Torino (TO), partita iva 11661350014 (nel seguito, in breve, &ldquo;Sport Grand Tour&rdquo;), ovvero sono da questa legittimamente utilizzati.</p>
                <p><strong>I</strong> <strong>presenti</strong> <strong>Termini</strong> <strong>di</strong> <strong>Utilizzo</strong> <strong>costituiscono</strong> <strong>pertanto</strong> <strong>un</strong> <strong>accordo</strong> <strong>vincolante</strong> <strong>tra</strong> <strong>l</strong><strong>'</strong><strong>Utente</strong> <strong>e</strong> <strong>Sport</strong> <strong>Grand</strong> <strong>Tour</strong><strong>, </strong><strong>nonch&eacute;</strong> <strong>tra</strong> <strong>le</strong> <strong>Organizzazioni</strong> <strong>Sportive</strong> <strong>e</strong> <strong>Sport</strong> <strong>Grand</strong> <strong>Tour</strong> <strong>per</strong> <strong>quanto</strong> <strong>riguarda</strong> <strong>l</strong><strong>'</strong><strong>utilizzo</strong> <strong>del</strong> <strong>Sito</strong> <strong>e</strong> <strong>di</strong> <strong>tutto</strong> <strong>il</strong> <strong>materiale</strong> <strong>in</strong> <strong>esso</strong> <strong>contenuto</strong> <strong>e</strong><strong>/</strong><strong>o</strong> <strong>della</strong> <strong>Piattaforma</strong><strong>.</strong></p>
                <p><strong>1) </strong><strong>Uso</strong> <strong>del</strong> <strong>Sito</strong> <strong>da</strong> <strong>parte</strong> <strong>degli</strong> <strong>Utenti</strong></p>
                <p>1.1 &ndash; E&rsquo; possibile accedere al Sito e utilizzarlo:</p>
                <p>(a) in qualit&agrave; di semplice visitatore (nel seguito, in breve, &ldquo;Utente/i Visitatore/i&rdquo;), senza l&rsquo;effettuazione di alcuna procedura di registrazione;</p>
                <p>(b) in qualit&agrave; di visitatore registrato (&ldquo;Utente/i Registrato/i&rdquo;), a seguito di specifica procedura di registrazione, con la creazione di un profilo personale per l&rsquo;accesso mediante credenziali al fine di gestire una prenotazione, richiedere informazioni, recensire una Organizzazione Sportiva, acquistare un prodotto/servizio.</p>
                <p>1.2 &ndash; Ai fini della registrazione, gli Utenti dovranno creare un proprio profilo, fornendo i seguenti dati:</p>
                <p>- indirizzo e-mail (dato obbligatorio);</p>
                <p>- <em>username</em> scelto (dato obbligatorio);</p>
                <p>- <em>password</em> scelta (dato obbligatorio);</p>
                <p>Attraverso la compilazione di specifici <em>form</em> visibili nel corso della navigazione sul Sito, inoltre, l&rsquo;Utente pu&ograve; prenotare e versare il contributo associativo e/o la quota per aderire all&rsquo;attivit&agrave; promossa dall&rsquo;organizzazione sportiva.</p>
                <p>I dati personali inseriti nei suddetti <em>form</em> di prenotazione/acquisto, come pure quelli forniti al momento della registrazione al Sito, ivi incluso l&rsquo;<em>Internet</em> <em>Protocol</em> <em>Address</em> (i.e. l&rsquo;etichetta numerica che identifica il dispositivo collegato ad una rete informatica da cui l&rsquo;Utente si connette al Sito) saranno trattati conformemente a quanto previsto nell&rsquo;informativa sul trattamento dei dati personali, di cui alla pagina https://www.orangogo.it/privacy.</p>
                <p>1.3 &ndash; L&rsquo;Utente pu&ograve; ricercare l&rsquo;attivit&agrave; sportiva che intende svolgere selezionando le attivit&agrave; sportive a cui intende aderire, sia effettuando una ricerca sia selezionando direttamente gli sport di proprio interesse.</p>
                <p>A seguito dei risultati di ricerca l&rsquo;utente pu&ograve; approfondire se l&rsquo;attivit&agrave; promossa dall&rsquo;Organizzazione sportiva soddisfa le proprie esigenze, grazie alla consultazione sia della pagina riservata all&rsquo;Attivit&agrave; stessa (Pagina Corso), sia della pagina dell&rsquo;Organizzazione Sportiva (Pagina Societ&agrave;). </p>
                <p>1.4 - Nella Pagina corso, l&rsquo;Utente trova tutte le informazioni relative all&rsquo;attivit&agrave; promossa dall&rsquo;Organizzazione Sportiva e segnatamente:</p>
                <p>- giorni e orari di svolgimento</p>
                <p>- fascia di et&agrave; a cui &egrave; rivolto</p>
                <p>- la durata del corso stesso (es. da settembre a giugno)</p>
                <p>- le disabilit&agrave; supportate</p>
                <p>- la descrizione del corso medesimo.</p>
                <p>Nella medesima pagina, inoltre, sono presenti alcuni <em>form</em> a disposizione dell&rsquo;Utente:</p>
                <ol>
                    <li>il <em>form</em> di prenotazione per fissare un incontro conoscitivo presso la sede dell&rsquo;Organizzazione Sportiva;</li>
                    <li>il <em>form</em> per inviare un messaggio all&rsquo;Organizzazione Sportiva che organizza le attivit&agrave;</li>
                    <li>il <em>form</em> di adesione all&rsquo;Organizzazione Sportiva le cui modalit&agrave; sono indicate contestualmente.</li>
                </ol>
                <p>1.5 - Il <em>form</em> di prenotazione &egrave; composto da:</p>
                <p>-&nbsp; un calendario per selezionare il giorno del primo incontro presso l&rsquo;Organizzazione Sportiva;</p>
                <p>- un campo di richiesta &ldquo;nome dello sportivo&rdquo;;</p>
                <p>- un campo di richiesta &ldquo;cognome dello sportivo&rdquo;;</p>
                <p>- un campo di richiesta di indicazione di un indirizzo mail dove venire ricontattati;</p>
                <p>- un campo di richiesta &ldquo;data di nascita&rdquo;;</p>
                <p>- link di accettazione dell&rsquo;informativa privacy.</p>
                <p>Perch&eacute; la prenotazione del corso sia effettiva occorre completare l&rsquo;inserimento di tutti campi indicati.</p>
                <p>A seguito dell&rsquo;invio del <em>form</em> di prenotazione, sia l&rsquo;Organizzazione sportiva che l&rsquo;Utente ricevono una mail di conferma e riassuntiva.</p>
                <p>1.6 &ndash; Il <em>form</em> per inviare un messaggio all&rsquo;Organizzazione Sportiva &egrave; composto da:</p>
                <p>- un campo di richiesta &ldquo;nome dello sportivo&rdquo;;</p>
                <p>- un campo di richiesta di indicazione di un indirizzo mail dove venire ricontattati;</p>
                <p>- un campo relativo all&rsquo;inserimento del testo del messaggio;</p>
                <p>- &nbsp; link per l&rsquo;accettazione dell&rsquo;informativa privacy.</p>
                <p>Una volta compilato il <em>form</em>, attraverso la Piattaforma, viene inviata una mail all&rsquo;Organizzazione Sportiva selezionata, che riporta il testo del messaggio inserito nel <em>form</em> medesimo.</p>
                <p>1.7 &ndash; Una volta presa visione delle attivit&agrave;, qualora si intendesse aderire agli obiettivi promossi dall&rsquo;Organizzazione Sportiva, &egrave; possibile per l&rsquo;utente effettuare l&rsquo;iscrizione online finalizzando gi&agrave; anche la somma da versare a titolo di contributo sportivo e/o la quota associativa.</p>
                <p>Il <em>form</em> di adesione &egrave; composto da:</p>
                <ul>
                    <li>un campo di richiesta &ldquo;dati della prenotazione&rdquo;;</li>
                    <li>un campo di richiesta &ldquo;visualizzazione carrello e conferma&rdquo;,</li>
                    <li>un campo di richiesta dati di fatturazione.</li>
                </ul>
                <p>Il versamento della somma relativa al contributo sportivo e/o quota associativa avviene attraverso una piattaforma esterna ad OrangoGo (<a href="https://stripe.com/it/payments">https://stripe.com/it/payments</a>). I dati inseriti, non vengono salvati sulla Piattaforma.</p>
                <p>1.8 &ndash; Nella Pagina societ&agrave; si trovano le informazioni relative alle Organizzazioni Sportive e segnatamente:</p>
                <p>- Ragione sociale Organizzazione Sportiva</p>
                <p>- Indirizzo della associazione/societ&agrave;</p>
                <p>- Tipologia di Ente (SSD, ASD etc..)</p>
                <p>- La natura dell&rsquo;Organizzazione Sportiva</p>
                <p>- La destinazione delle attivit&agrave; (es: soli associati)</p>
                <p>- Nominativo del Presidente</p>
                <p>- Composizione del Consiglio Direttivo</p>
                <p>- Modalit&agrave; per associarsi (es: contributo quota associativa prevista)</p>
                <p>- Descrizione delle attivit&agrave;</p>
                <p>- Sport promossi</p>
                <p>- Corsi organizzati</p>
                <p>- Campi estivi organizzati</p>
                <p>- Promozioni ed eventi</p>
                <p>- Recensioni e valutazioni</p>
                <p>Su questa pagina &egrave; di nuovo presente il <em>form</em> per inviare un messaggio all&rsquo;Organizzazione Sportiva di cui al precedente punto 1.6</p>
                <p>1.9 A ciascun Utente Registrato, previo accesso a mezzo delle credenziali comunicate a seguito della registrazione, &egrave; consentito esprimere un parere sulle attivit&agrave; promosse dalle Organizzazioni Sportive sulla Piattaforma, nonch&eacute; recensire nel complesso l&rsquo;Organizzazione Sportiva medesima. Ciascun Utente Registrato potr&agrave; esprimere un giudizio esclusivamente in relazione a attivit&agrave; effettivamente svolte. Tale processo pu&ograve; avvenire sia utilizzando un codice univoco che &egrave; stato rilasciato all&rsquo;Utente dall&rsquo;Organizzazione Sportiva, sia utilizzando appositi link forniti a seguito dell&rsquo;avvenuta adesione.</p>
                <p><strong>2) </strong><strong>Utilizzo</strong> <strong>del</strong> <strong>Sito</strong> <strong>e</strong> <strong>della</strong> <strong>Piattaforma</strong> <strong>da</strong> <strong>Parte</strong> <strong>delle</strong> <strong>Organizzazioni</strong> <strong>Sportive</strong></p>
                <p>2.1 &ndash; La Piattaforma &egrave; un applicativo accessibile in Cloud tramite strumenti di orientamento educativi motori e psicologici che costituiscono un supporto all&rsquo;individuazione dell&rsquo;attivit&agrave; sportiva pi&ugrave; appropriata per il singolo individuo. Una volta individuato lo sport, la piattaforma aiuta l&rsquo;utente a selezionare l&rsquo;Organizzazione Sportiva che promuove l&rsquo;attivit&agrave; prescelta. La piattaforma provvede quindi a dotare le Organizzazioni Sportive di un software di gestione delle adesioni online.</p>
                <p>2.2 &ndash; Al fine di utilizzare la Piattafoma le Organizzazioni Sportive devono registrarsi, fornendo i seguenti dati:</p>
                <p>Nome della Societ&agrave; o Associazione</p>
                <p>Indirizzo della Sede Legale</p>
                <p>OrangoGo pu&ograve; in qualsiasi momento inserire o rimuovere campi richiesti con la finalit&agrave; di fornire un&rsquo;informativa puntuale e precisa agli utenti che si trovano nella necessit&agrave; di scegliere quale Organizzazione Sportiva risponde alle proprie esigenze</p>
                <p>I dati forniti al momento della registrazione al Sito, ivi incluso l&rsquo;Internet Protocol Address (i.e. l&rsquo;etichetta numerica che identifica il dispositivo collegato ad una rete informatica l&rsquo;Organizzazione sportiva si connette al Sito), come pure quelli che saranno forniti al momento della pubblicazione di contenuti sul sito medesimo, saranno trattati conformemente a quanto previsto nell&rsquo;informativa sul trattamento dei dati personali, di cui alla pagina https://www.orangogo.it/privacy.</p>
                <p>2.3 - A seguito della registrazione, all&rsquo;Organizzazione verr&agrave; assegnato un account, accessibile mediante le credenziali scelte (<em>User</em> <em>ID</em> e <em>password</em>), delle quali l&rsquo;Organizzazione Sportiva &egrave; unica ed esclusiva titolare e responsabile, anche del loro utilizzo.</p>
                <p>E&rsquo; fatto obbligo all&rsquo;Organizzazione Sportiva di comunicare immediatamente a Sport Grand Tour qualsiasi utilizzo non autorizzato e/o improprio dell&rsquo;account e delle relative credenziali di accesso, nonch&eacute; qualsivoglia utilizzo illecito degli stessi, riservandosi Sport Grand Tour la facolt&agrave; di disabilitare l&rsquo;accesso al Sito, come pure la sua eventuale riattivazione, a suo insindacabile giudizio. </p>
                <p>2.4 Per facilitare la ricerca dell&rsquo;Organizzazione Sportiva che persegue lo scopo a cui l&rsquo;ipotetico utente potrebbe aderire, si precisa che l&rsquo;Organizzazione Sportiva autorizza Sport Grand Tour a rendere i contenuti pubblici visibili su OrangoGo anche mediante indicizzazione (automatica o selettiva) su motori di ricerca.</p>
                <p>2.5 Per ottimizzare l&rsquo;individuazione delle Organizzazioni Sportive OrangoGo intende utilizzare anche Google My Business, proponendo anche la gestione delle schede del suddetto servizio relative alle singole Organizzazioni Sportive previa autorizzazione espressa delle stesse. I dati con i quali verr&agrave; compilata la scheda Google My Business saranno gli stessi forniti ed aggiornati dalle Organizzazioni Sportive per la compilazione della propria pagina su orangogo.it e per gli stessi vale la stessa limitazione di responsabilit&agrave; di cui al all&rsquo;art.6 dei presenti termini e condizioni d&rsquo;uso.</p>
                <p><strong>3) </strong><strong>Recensioni</strong></p>
                <p><strong>3.1 </strong>Agli Utenti &egrave; data la facolt&agrave; di esprimere una valutazione sull&rsquo;Organizzazione Sportiva, sull&rsquo;Attivit&agrave; svolta e sugli Impianti Sportivi (la &ldquo;<strong>Recensione</strong>&rdquo;).</p>
                <p><strong>3.2</strong> Sport Grand Tour si impegna a rendere disponibili sul sito tali Recensioni, senza alcun obbligo di verifica preventiva delle stesse, il cui contenuto, pertanto, resta di esclusiva responsabilit&agrave; dell&rsquo;Utente che lo ha inserito. In ogni caso, Sport Grand Tour, anche su esplicita segnalazione in tal senso, si riserva il diritto di negare, revisionare o cancellare Recensioni ritenute, a suo insindacabile giudizio, non idonee, non attendibii o di contenuto ingiurioso, oltraggioso, diffamatorio o comunque illecito, ivi inclusi quelli che violino i diritti di propriet&agrave; industriale e intellettuale di terze parti.</p>
                <p>3.3 Le Recensioni, una volta pubblicate sul Sito e sulla Piattaforma, sono a uso esclusivo di Sport Grand Tour e possono essere resi disponibili sul Sito e sulla Piattaforma secondo le modalit&agrave; stabilite da Sport Grand Tour medesima. L&rsquo;Organizzazione Sportiva non potr&agrave;, n&eacute; direttamente n&eacute; indirettamente, pubblicare, pubblicizzare, promuovere, copiare, ricavare, riportare tramite link, integrare, ottenere, utilizzare, combinare, condividere e in nessun altro modo utilizzare i giudizi degli Utenti in assenza di un'approvazione scritta da parte di Sport Grand Tour<strong>.</strong> </p>
                <p><strong>4) </strong><strong>Diritto</strong> <strong>d</strong><strong>&rsquo;</strong><strong>autore</strong></p>
                <p>4.1 - Sport Grand Tour &egrave; l&rsquo;unico autore del database e detiene i diritti d&rsquo;autore in merito alla strutturazione e all&rsquo;organizzazione dei contenuti</p>
                <p>4.2 - L'intero contenuto del Sito, compreso il <em>design</em>, i testi, il <em>lay</em><em>-</em><em>out</em>, i disegni, le foto, i filmati, la grafica e tutti gli altri elementi delle pagine del Sito, nonch&eacute; la loro selezione e disposizione, sono di titolarit&agrave; esclusiva di Sport Grand Tour, che ne detiene i relativi diritti d&rsquo;autore, ovvero sono incluse e utilizzate nel Sito con l&rsquo;autorizzazione del legittimo titolare del relativo diritto. In particolare, i diritti d&rsquo;autore sul contenuto delle pubblicazioni di contenuti di qualsivoglia genere (immagini, video, testi, schede di presentazione, ecc.) effettuate dalle Organizzazioni Sportive o soggetti terzi (le &ldquo;Pubblicazioni&rdquo;) sono di titolarit&agrave; dei singoli aventi diritto, i quali hanno dichiarato a Sport Grand Tour di avere sulle stesse tutti i diritti e relative autorizzazioni.</p>
                <p>4.3 - &Egrave; vietato qualsivoglia utilizzo, anche parziale, dei materiali contenuti nel Sito, ivi inclusa la riproduzione, l'adattamento, la modifica, la traduzione, la distribuzione ovvero la pubblicazione, se non a seguito di preventiva autorizzazione scritta da parte di Sport Grand Tour o dei singoli aventi diritto.</p>
                <p>4.4 - Resta comunque inteso che qualsiasi forma di riproduzione di materiali dal Sito non conferisce all'Utente alcun titolo o diritto su di essi, ivi incluso il <em>software</em> utilizzato nel Sito, che resta di titolarit&agrave; esclusiva del soggetto che l&rsquo;ha fornito a Sport Grand Tour.</p>
                <p><strong>5) </strong><strong>Marchi</strong></p>
                <p>5.1 - Tutti i marchi e i segni distintivi riprodotti nel Sito, compreso il nome a dominio, sono di esclusiva titolarit&agrave; di Sport Grand Tour ovvero di terzi che ne hanno concesso a Sport Grand Tour il legittimo utilizzo. In particolare, i marchi contenuti nelle Pubblicazioni sono di titolarit&agrave; dei singoli aventi diritto.</p>
                <p>5.2 - Pertanto, l&rsquo;utilizzo dei suddetti marchi e segni distintivi deve intendersi vietato, salvo espressa autorizzazione scritta da parte di Sport Grand Tour.</p>
                <p>5.3 - Qualsivoglia collegamento al Sito (ad esempio nella forma del c.d. <em>linking</em> o del c.d. <em>framing</em>) deve essere previamente ed espressamente autorizzato per iscritto da parte di Sport Grand Tour.</p>
                <p><strong>6) Diritto sui generis</strong></p>
                <p>6.1Sport Grand Tour &egrave; il maker della banca dati della piattaforma/sito.</p>
                <p>6.2Sport Grand Tour detiene in via esclusiva il diritto sui generis per quanto concerne l&rsquo;estrazione, intesa come attivit&agrave; di trasferimento permanente o temporaneo di una parte sostanziale o totale dei dati del database su altro supporto con qualsiasi mezzo o in qualsivoglia forma e il diritto sui generis per il reimpiego dei dati stessi, mediante qualsiasi forma di messa a disposizione del pubblico della totalit&agrave; o di una parte sostanziale del contenuto della banca dati mediante distribuzione di copie, noleggio, trasmissione in linea o in altre forme.</p>
                <p>Sport Grand Tour ha quindi il diritto esclusivo di controllare le attivit&agrave; di trasferimento e di reimpiego dei dati costituenti il database.</p>
                <p><strong>7) </strong><strong>Limitazione</strong> <strong>di</strong> <strong>responsabilit&agrave;</strong></p>
                <p>7.1 &ndash; L&rsquo;Utente e le Organizzazioni Sportive garantiscono che le informazioni fornite all&rsquo;atto della registrazione al Sito Orangogo.it e nel corso dell&rsquo;utilizzo dello stesso e della Piattaforma siano veritiere, complete, corrette e aggiornate. L&rsquo;Utente e le Organizzazioni Sportive saranno pertanto responsabili per qualsivoglia attivit&agrave; compiuta sulla &nbsp;, anche per loro conto, nonch&eacute; di ogni pregiudizio che dovesse derivare a carico di Sport Grand Tour ovvero di terzi a seguito dell&rsquo;utilizzo non autorizzato e illecito del rispettivo proprio account e delle rispettive credenziali di accesso.</p>
                <p>7.2 &ndash; In ogni caso, Sport Grand Tour declina ogni responsabilit&agrave; rispetto ad imprecisioni nelle informazioni e nelle descrizioni delle Organizzazioni Sportive, o altri dati resi disponibili sul Sito, come pure in merito alle opinioni espresse nelle valutazioni e recensioni, in relazione alle quali Sport Grand Tour non &egrave; tenuta ad esercitare alcun controllo preventivo.</p>
                <p>7.3 - Sport Grand Tour adotta una procedura di segnalazione degli abusi nelle Pubblicazioni delle Organizzazioni Sportive, come pure nelle recensioni/valutazioni effettuate in relazione alle Organizzazioni Sportive medesime ritenute contrarie alla legge, all&rsquo;ordine pubblico o al buon costume, ivi incluso materiale in violazione della normativa a tutela della propriet&agrave; industriale o intellettuale. Conseguentemente, nel caso in cui un Utente e/o l&rsquo;Organizzazione Sportiva abbia un'obiezione o un reclamo concernente il contenuto delle suddette Pubblicazioni potr&agrave; inviare la segnalazione a Sport Grand Tour all&rsquo;indirizzo info@orangogo.it. Sport Grand Tour adotter&agrave;, entro un termine ragionevole, le misure ritenute, a proprio insindacabile giudizio, pi&ugrave; opportune anche al fine della rimozione del materiale segnalato.</p>
                <p>7.4 - Il sito pu&ograve; essere utilizzato esclusivamente da Utenti di maggior et&agrave;.</p>
                <p>I soggetti che, esercitando potest&agrave; parentale sui minori, consentano loro l'uso del Sito, si rendono responsabili del comportamento on line del minore, del controllo dell'accesso e delle conseguenze in caso di abuso da parte del minore.</p>
                <p>7.5 &ndash; Sport Grand Tour declina qualsivoglia responsabilit&agrave; per eventuali danni che possano derivare alle apparecchiature informatiche degli Utenti a seguito dell'accesso al Sito o dell'impossibilit&agrave; di accedere al Sito, incluso danni alle apparecchiature informatiche degli Utenti derivanti da virus.</p>
                <p>7.6 - In particolare, Sport Grand Tour non rilascia alcuna dichiarazione o garanzia in base alla quale:</p>
                <p>-&nbsp; l&rsquo;Utente e l&rsquo;Organizzazione Sportiva saranno in grado di utilizzare il Sito, che il Sito o il suo contenuto non conosceranno interruzioni o che continueranno ad essere messi a disposizione nella sua forma attuale o in qualsiasi altra forma;</p>
                <p>-&nbsp; il Sito o qualsiasi <em>software</em> disponibile sullo stesso o dallo stesso scaricato saranno esenti da virus o difetti e compatibili con l'apparecchiatura dell'Utente.</p>
                <p>7.7 - Sport Grand Tour non rilascia alcuna garanzia circa l&rsquo;accuratezza, la completezza, e l&rsquo;affidabilit&agrave; delle informazioni e dei materiali contenuti nel Sito. Inoltre, Sport Grand Tour non garantisce che le valutazioni e le recensioni degli Utenti Registrati siano stati espressi a seguito di una frequentazione effettiva delle Organizzazioni Sportive presenti sulla Piattaforma.</p>
                <p>7.8 - Il Sito potrebbe contenere riferimenti a prodotti e/o servizi forniti da terzi o collegamenti a siti esterni, non gestiti da Sport Grand Tour e per il cui contenuto Sport Grand Tour non potr&agrave; essere conseguentemente ritenuta responsabile. Sport Grand Tour non fornisce alcuna garanzia circa il contenuto dei suddetti siti e ciascuno decider&agrave; di accedervi e di consultarli esclusivamente a proprio rischio. L&rsquo;inclusione nel Sito di riferimenti a prodotti e/o servizi forniti da terzi o collegamenti a siti esterni non implica alcuna forma di pubblicit&agrave; o sponsorizzazione degli stessi da parte di Sport Grand Tour.</p>
                <p><strong>8) </strong><strong>Disposizioni</strong> <strong>finali</strong></p>
                <p>8.1- I presenti Termini di Utilizzo sono disponibili esclusivamente in lingua italiana.</p>
                <p>8.2 - I presenti Termini di Utilizzo sono disciplinati dalla legge italiana.</p>
                <p>8.3 - Sport Grand Tour si riserva il diritto di modificare il Sito e i presenti Termini di Utilizzo in qualsiasi momento. Delle modifiche verr&agrave; data comunicazione sul Sito e gli Utenti continueranno ad usare il Sito secondo la versione modificata dei Termini di Utilizzo. </p>
                <p>8.4 &ndash; Sport Grand Tour si riserva inoltre il diritto di modificare, sospendere o cessare in ogni momento qualsivoglia servizio offerto, compresa la disponibilit&agrave; di ciascuna banca dati o di suoi specifici contenuti. Sport Grand Tour si riserva anche il diritto di impedire l&rsquo;accesso a uno o pi&ugrave; Utenti e/o Organizzazioni Sportive, anche senza alcun preavviso, per ragioni tecniche o per motivi di sicurezza, quali, a mero titolo esemplificativo, prevenire accessi non autorizzati al Sito, perdita o distruzione di dati.</p>
                <p>8.5 - Qualsivoglia comunicazione relativa ai presenti Termini di Utilizzo dovr&agrave; essere effettuata per iscritto e si intender&agrave; efficacemente e validamente eseguita al ricevimento della stessa, se effettuata a mezzo posta elettronica, a mezzo fax o a mezzo posta ai seguenti recapiti:</p>
                <p>-&nbsp; per le comunicazioni effettuate a mezzo del servizio postale: Sport Grand Tour s.r.l., Corso Valdocco 2, , 10122 Torino (TO);</p>
                <p>-&nbsp; per le comunicazioni effettuate a mezzo e-mail: <a href="mailto:info@orangogo.it">info@orangogo.it</a></p>
            </div>
        </div>
    </div>
@endsection
